language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
matrix:
  allow_failures:
    - python: "2.7"
    - python: "3.7-dev"
  fast_finish: true

addons:
  apt:
    packages:
     - dssp
env:
  global:
    - VERMOUTH_TEST_DSSP=mkdssp
    - SKIP_GENERATE_AUTHORS=1
    - SKIP_WRITE_GIT_CHANGELOG=1
install:
  - pip install --upgrade codecov pytest-cov
  - pip install --upgrade .
script:
  - pytest -vv --cov=vermouth vermouth 
after_success:
  - codecov

jobs:
  include:
    - stage: docs
      python: "3.5"
      addons: skip
      install:
        - pip install --upgrade -r requirements-docs.txt
        - pip install --upgrade .[full]
      # script: python setup.py build_sphinx
      script: mkdir -p doc/source/_static; sphinx-build -EnW -b html doc/source/ doc/build/html
      after_success: skip
    - stage: pylint
      python: "3.5"
      addons: skip
      install:
        - pip install pylint
      script:
          # Run Pylint, extract the line that looks like " 9.53/10", and
          # extract the score. Compare the score to 9.5 ("\1>9.5"). Fail if
          # lower, success if higher. There's probably also a way to get the
          # output on screen as well. But meh.
        - [ $(bc -l <<< $(pylint vermouth | sed -re 's_.* ([0-9\.]+)/10.*_\1>9.5_;t;d')) -eq 1 ] 
        - [ $(bc -l <<< $(pylint bin/martinize2 | sed -re 's_.* ([0-9\.]+)/10.*_\1>9.5_;t;d')) -eq 1 ] 
        # - pylint vermouth
        # - pylint bin/martinize2
      after_success: skip
#   - stage: deploy
#     python: "3.5"
#     addons: skip
#     env:
#     script: skip
#     after_success: skip
#     deploy:
#         user: ...
#         password:
#             # travis encrypt --add deploy.password
#             secure: ...
#         provider: pypi
#         on:
#             tags: true

