language: python
cache: pip
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.5-dev"
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"
matrix:
    allow_failures:
        - python: "2.7"
        - python: "3.4"
        - python: "3.7-dev"
addons:
    apt:
        packages:
            - dssp
env:
    - VERMOUTH_TEST_DSSP=mkdssp
install:
    - pip install pylint
    - pip install --upgrade .
script:
    - pytest -vv vermouth
after_script:
    - pylint vermouth
    - pylint bin/martinize2
